### ISSUE TITLE
Cannot run mojito-perf if I don't use the mojito CLI

### ISSUE THREAD

**Issue by jlecomte** [YahooArchive/mojito#1042]
I start Mojito without using the CLI (mojito start) and it seems like a recent regression prevents me from running mojito-perf that way. Indeed, I set the following in my config:

"settings": ["master"],

"perf": {
    "logFile": "/tmp/mojito-search-apps-news-perf.log",
    "timeline": true,
    "mark": true
}

The logFile setting is not used because of this line:

https://github.com/yahoo/mojito/blob/develop/lib/mojito.js#L300

I think this line should be changed to use the config if no option is available.

**Comment by caridy** [comment]
@jlecomte `logFile` was never intended to be defined in application.json, it is a cli only option. In order to collect perf information you need two things:
- perf config in `application.json` (to enable `timeline`, `mark`, etc.)
- `mojito start --perf` or `mojito start --perf something.log` or `mojito start --perf each{req}.log`

aside from that, remember to use the profiler to generate the nice charts, e.g:

`mojito profiler --input something.log`
