### ISSUE TITLE
Mojito page Get Started link points to wrong URL

### ISSUE THREAD

**Issue by oyving** [YahooArchive/mojito#1179]
The "Get Started" link at http://developer.yahoo.com/cocktails/mojito/ points to the wrong page. It points to  http://developer.yahoo.com/cocktails/mojito/docs/quickstart/, but according to issue #1176 it is no longer valid and should point to http://developer.yahoo.com/cocktails/mojito/docs/getting_started/quickstart.html

**Comment by zhouyaoji** [comment]
Thanks, @oyving. I've updated the link in the page. Sorry about the confusion. The quickstart was a separate document at one point, then later folded into the Getting Started chapter. After the quickstart was published to a different URL, the original quickstart was not deleted from the server, and the links, which weren't broken because of the errant page), were not updated. The problem is hopefully resolved now.
