### ISSUE TITLE
pageData not updated after mojitProxy.invoke

### ISSUE THREAD

**Issue by lazybean** [YahooArchive/mojito#1234]
Hi !

I'm not sure wether it is a bug or just me doing something weird.

In my controller I use both data and pageData to store current date.
At the first load, everything is fine.

But when in my binder , I use mojitProxy.invoke to invoke the same index action, the pageData is not updated, where data is.

Here is an exemple :  https://gist.github.com/lazybean/6148cbb6fa8f721c988c

mojito version is 0.7.2

**Comment by caridy** [comment]
`pageData` is not going to be preserved under a RPC call, which means that we don't pass the pageData back and forward when making tunnel requests. This is a limitation because we can't not predict the size of the pageData, and we can't, at the moment, resolve conflicts between what comes back from a tunnel request and what was potentially changed in the client side at the page level. For that you should use the `data`, which is more self contained for the mojit instance, but it doesn't mean you will not running in conflicts, until we introduce the latency compensation mechanism.

What you can do is to use `data` just to transport the value, then once in the callback in the binder, you can set the value at the page level, which will triggers the change event, and it is your responsibility to keep the `pageData` and the `data` in sync.

/cc @zhouyaoji we should probably add this a _potential issue_ under: http://developer.yahoo.com/cocktails/mojito/docs/topics/mojito_data.html#sharing-data

**Comment by lazybean** [comment]
Thanks à lot for the explanation. 
I understand the limitation and will deal with it as you advise.

I agree it would be worth to mention this in the documentation.
