### ISSUE TITLE
'null' values inside server side view template causes server crash

### ISSUE THREAD

**Issue by mridgway** [YahooArchive/mojito#132]
Mustache templates rendered on the server side will crash the server if given a null value. This may be fixed by https://github.com/yahoo/mojito/pull/116 but it looks like the rendering code does the same thing: https://github.com/raycmorgan/Mu/blob/master/lib/mu/renderer.js#L90

Mojito should either catch this and handle it gracefully or Mu2 should properly handle null values as an empty string (if it doesn't already).

**Comment by drewfish** [comment]
I'm hoping that the Mu upgrade will fix this too.  (In my mind this is just an issue with the templating engine (mu) and not with the Mojito framework.)

**Comment by taomin** [comment]
Shouldn't mojito catch the error if mu fail for any reason ?  letting server die is not a good idea since any dependent library can fail,

**Comment by isao** [comment]
true...

**Comment by mridgway** [comment]
So I just ran a test with the updated Mu2 and it still fails with nulls being passed to the templates. I think we need to fix this at both ends: open a ticket against Mu2 and add some error handling to Mojito.

**Comment by mridgway** [comment]
Created a ticket against Mu: https://github.com/raycmorgan/Mu/issues/28

**Comment by mridgway** [comment]
It looks like the issue has been fixed in Mu. Maybe it's worth doing another PR for the latest version?

**Comment by isao** [comment]
This issue should be fixed in ours too... 

We could have this and similar (like your DaliProxy PR) released as npm installable bundles. This would make features available for opt-in and make a ramp for real-world testing...

On Jul 16, 2012, at 8:12 PM, "Michael Ridgway" reply@reply.github.com wrote:

It looks like the issue has been fixed in Mu. Maybe it's worth doing another PR for the latest version?

---
