### ISSUE TITLE
custom yui module invisible in test

### ISSUE THREAD

**Issue by jianglibo** [YahooArchive/mojito#1333]
in controller.server.js requries my custom 'model-decorator' module,but Y.mojito.ModelDecorator is null.

**Comment by caridy** [comment]
this is the principle of unit testing, you test the unit, not its dependencies. you will have to mock `Y.mojito.ModelDecorator` in order to tests `controller.server.js`. there are plenty of examples thru the documentation for how to mock things when testing: http://developer.yahoo.com/cocktails/mojito/docs/topics/mojito_testing.html#mocking-models
