### ISSUE TITLE
after ac.cookie.set() ac.cookie.get() returns "undefined" - bug?

### ISSUE THREAD

**Issue by d-adamkiewicz** [YahooArchive/mojito#1384]
Excerpt from mojits/MyMojit/controller.server.js (single mojit, no HTMLFrameMojit used)

``` javascript
 index: function(ac) {
            ac.models.get('model').getData(function(err, data) {
                var cookie = ac.cookie.get("sid");
                if (!cookie) {
                    console.log('no cookie set');
                    ac.cookie.set("sid", new Date().getTime());
                    console.log('ac.cookie.set()');
                    cookie = ac.cookie.get("sid");
                }
                console.log('cookie: ' + cookie);
                if (err) {
                    ac.error(err);
                    return;
                }
                ac.assets.addCss('./index.css');
                ac.done({
                    status: 'Mojito is working.',
                    data: data
                });
            });
        }
```

_When 'someIP:8666' url opened in browser this produces on console:_
debug: (mojito-dispatcher): Dispatcher created
no cookie set
ac.cookie.set()
cookie: undefined
info: (outputhandler.server): done
mojito: (outputhandler.server): END
debug: (mojito-dispatcher): Dispatcher created
cookie: 1403438214809
info: (outputhandler.server): done
mojito: (outputhandler.server): END

---

It looks like ac.cookie.set() is setting cookie (I can see it in FF/Chrome), but ac.cookie.get() can't get the value- on next request however ac.cookie.get() returns previously set cookie value. IMHO problem leads deeper but I can't debug it

**Comment by aljimenez** [comment]
Hi,

Thanks for reporting this. To my understanding this is the expected behavior; ac.cookie.get gets the cookies from the request, whereas ac.cookie.set sets new cookies for the response. So when you call ac.cookie.set the client will get the new cookie, but when you call ac.cookie.get right after, the cookies returned should be the original set of cookies that the client sent, not the new cookies that will be sent back. This is slightly different from what you would expect when using Y.Cookie on the client side. Let me know if you have any questions.

Thanks,
Albert

**Comment by d-adamkiewicz** [comment]
Hi,
Thank you for the anwser. What I try to do is to make sure whether cookie was set (and its value) or not in single execution of server controller code where app logic needs this confimation because I want link some server stored data with it - ie implement sessions.btw. implementation ac.cookie.get() changed recently? Mojito sessions https://github.com/akshar100/mojito-session addon which was starting point for me uses it "wrong way".

**Comment by aljimenez** [comment]
Based on the [history of cookie.server.js](https://github.com/yahoo/mojito/commits/develop/lib/app/addons/ac/cookie.server.js), the implementation has been the same since 2012. I am not familiar with mojito-session, but if you end up creating your own solution, you may consider open sourcing it so others can benefit from it.
