### ISSUE TITLE
Broken links at https://github.com/yahoo/mojito/

### ISSUE THREAD

**Issue by rwaldura** [YahooArchive/mojito#173]
https://github.com/yahoo/mojito/ includes the file README.md. 
All links in the "licensing and contribution" section are broken.
(Such relative links only work when I'm displaying the README document itself -- they don't work from the embedded file).

**Comment by isao** [comment]
fixed with pull #195. I moved these to the wiki. You can edit or git/clone/edit/push from there right now.

Rationale: multiple versions can be considered public/published at the same time, absolute links to the github code browser didn't feel right, and relative links no longer work in the main page vs the branch pages.
