### ISSUE TITLE
[Enhancement] Provide configuration object to view engine wrapper

### ISSUE THREAD

**Issue by imalberto** [YahooArchive/mojito#208]
Some context:
- MU is the "rendering framework" used by mojito (but this should apply to any "rendering framework", not just MU)
- Mojito provides custom wrapper around "rendering framework" (e.g. mu.&lt;affinity&gt;.js)

Motivation:
- Mojito specific view engine wrapper should have some flexibility to implement custom behavior based on rendering framework capability and application requirement
- By providing options to the view engine wrapper, implementation can be customised

Proposal:

<pre><code>
// application.json
[
    {
        "viewEngine": {
            // this can be per "rendering framework"
            // custom options here, only the view engine wrapper knows about e.g.
            "bufferOutputAdapter": true
        }
    }
]
</code></pre>

**Comment by drewfish** [comment]
I think the key should be `"viewEngine"` _only_ if the config details apply to all view engines.  (Our "mu" view engine is just one, there can be others.)

Note to implementer: it looks like Mojito instantiates the ViewRenderer in the following three places, all of which have access to the application config:  `app/addons/ac/output-adapter.common.js`, `app/addons/ac/partial.common.js`, and `app/autoload/mojito-client.client.js`.  It seems like the approach is to change the API for ViewRenderer and the view engines to take config from application.json.  (Please use an "options" argument which is an object, so that we can add new things later without relying on argument order.) This API change will likely be a backwards-compatibility breaking change, but it should affect a minority of users (only those who've written their own view engines).

**Comment by mridgway** [comment]
See #371 for fix.
