### ISSUE TITLE
Broken link in ActionContext documentation!

### ISSUE THREAD

**Issue by rmadhuram** [YahooArchive/mojito#220]
http://developer.yahoo.com/cocktails/mojito/docs/api_overview/mojito_action_context.html

The link to API docs is broken - http://developer.yahoo.com/cocktails/mojito/api/Y.mojito.ActionContext.html

Raj

**Comment by rmadhuram** [comment]
I found the broken link here as well: http://developer.yahoo.com/cocktails/mojito/docs/reference/glossary.html 
Looks like the API docs were re-parented and that was not reflected in docs that were pointing to it.

**Comment by rwaldura** [comment]
Joe?

**Comment by rmadhuram** [comment]
When fixing this, you may also want to fix the typo "Using Query Paramaters" in http://developer.yahoo.com/cocktails/mojito/docs/

Thanks,
Raj

**Comment by zhouyaoji** [comment]
I've fixed the links to the ActionContext Class in both the API Overview and Glossary chapters. I fixed the misspelling in the Mojito Documentation Directory (http://developer.yahoo.com/cocktails/mojito/docs/), but I was not able to publish the updated page to YDN because of a server error. I have contacted the SEs for YDN, so the problem should be resolved soon. Thanks for catching those mistakes!

**Comment by zhouyaoji** [comment]
I've merged a pull request with the updated docs. The source file for the documentation directory is not part of the GitHub repo, so I'm closing this bug. I will follow up with YDN if the documentation directory is not updated. Thanks.
