### ISSUE TITLE
Is it possible to swap out YUITest with Jasmine or Mocha?

### ISSUE THREAD

**Issue by trungpham** [YahooArchive/mojito#256]
n/t

**Comment by rwaldura** [comment]
Is it probably possible, but we've never looked into it.
What is your motivation for wanting to do so?

**Comment by trungpham** [comment]
I like mocha and jasmine syntax better. Less verbose. And mocha has better
support for async testing.
On Jul 10, 2012 12:14 PM, "Renaud Waldura" <
reply@reply.github.com>
wrote:

**Comment by rwaldura** [comment]
Oh, very interesting! 
Would you be willing to do an experiment in your fork and show us what it looks like?

**Comment by isao** [comment]
you should be able to do unit testing however you like. To swap it out, you can put a module `mojito-cli-cmd-test` in your require path and it will be run instead of `mojito test`. also, fyi we will be improving our test system, but not to the exclusion of other test runners/frameworks.

if you come up with something, please share. :)
