### ISSUE TITLE
Mojito fails in IE6/7 and IE10 (compatibility IE7)

### ISSUE THREAD

**Issue by focuzz8** [YahooArchive/mojito#262]
Using Mojito in IE6/7 linked with problem - events module of yui fails when using binders (it seems like this bug is linked with yui bug http://yuilibrary.com/projects/yui3/ticket/2531547)

**Comment by rwaldura** [comment]
@focuzz can you describe the problem a bit more? what functionality is broken?

**Comment by focuzz8** [comment]
Yes, sample app https://github.com/focuzz/mj-defer-demo (just app, with just mojit with defer true). Works in FF, Crome etc. Fails in IE6/7. Fails at mojito/autoload/output-handler.client.js on line 101 (Unable to get property 'indexOf' of undefined or null reference) - headers contains 'content-type'.

**Comment by caridy** [comment]
@focuzz can you try that example with this setting in the application.json:

```
    "yui": {
        "dependencyCalculations": "precomputed+ondemand"
    }
```

It is just a hunch, but I guess this problem is related with the fact that old IE versions require some YUI specific modules, and since the default behavior in mojito is "precomputed", it fails badly in those escenarios.

If this fix the problem for your example with the latest mojito, that means we should set "precomputed+ondemand" as the default behavior, and eventually introduce a new one to use the new features in YUI 3.6.x to optimize the loader metadata per request.

**Comment by focuzz8** [comment]
Didn't help... Will try to dig more deep in evening.

**Comment by rwaldura** [comment]
Thanks @focuzz , let us know what you find out!

**Comment by caridy** [comment]
This should not be an issue anymore in 0.5.x since YUI loader will load IE specific bundles when needed. Closing this.  @focuzz, feel free to reopen it.
