### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by rmadhuram** [YahooArchive/mojito#272]
http://developer.yahoo.com/cocktails/mojito/docs/code_exs/query_params.html 

Link to http://developer.yahoo.com/cocktails/mojito/api/Params.common.html is broken (Params addon)

Suggest using a spider to catch all broken links.

-Raj

**Comment by rwaldura** [comment]
Thanks @rmadhuram!
I like the spider suggestion. Joe, how could we do this?

**Comment by rwaldura** [comment]
For the record, all the documentation is checked-in and available in the source tree at e.g.
https://github.com/yahoo/mojito/blob/develop/docs/dev_guide/code_exs/query_params.rst

**Comment by zhouyaoji** [comment]
I was told that YDN was doing link checking as part of their QA. I personally used a link checker before publishing the docs to YDN, but the API docs have changed because of API changes and the latest API docs were generated by yuidoc.js instead of the old YUIDoc that used Python. As a result, the URLs for the API docs changed and broke links. I'll contact the YDN team and do another link check for the time being.
