### ISSUE TITLE
Defer route computation in ac so it's driven by mojit requests only.

### ISSUE THREAD

**Issue by mojit0** [YahooArchive/mojito#277]
We are executing almost 33 mojits for our Application's home page. Some of these are dynamic mojits created through ac.composite.execute(cfg, … ).

While going though mojito code (e.g. lib/app/autoload/dispatch.common.js, lib/app/autoload/resource-store-adapter.common.js, lib/store.server.js) I realized that for all these mojits, certain common code is run.

E.g. getRoutes from store.server.js is called for all the mojits.

All mojits need not be aware of contents of routes.json.

**Comment by rwaldura** [comment]
didn't we do this already? #252
re-open if I'm wrong

**Comment by isao** [comment]
yes that landed in 0.3.30

**Comment by mridgway** [comment]
This issue encompasses several things that should be optimized in the creation of the AC object. The change that landed in 0.3.30 only made it so that the RouteMaker was instantiated if the url addon was used (before it was instantiated regardless of being used).

The example that this description calls out is the action-context passing store.getRoutes() into each mojit. That's a lot of data being passed around that seems unnecessary. It seems like the route-maker should be instantiated once per process and hold on to the data that it needs instead of passing all of the data to the child mojits.
