### ISSUE TITLE
Can we add a class for the body for HTMLFrameMojit ?

### ISSUE THREAD

**Issue by kinlum** [YahooArchive/mojito#947]
It seems that there was no existing method to add a class / classes for the `body` element if using `HTMLFrameMojit` ?  Is it possible that it is added as a feature?

**Comment by caridy** [comment]
It will be posible in the next iteration: 0.5.3 coming up in the next few days.

In this new version, creating a custom HTMLFrame will be a breeze, in which case you will have full control over the capabilities of your frame, and we will encourage people to have their own frame rather than using the one shipped with mojito, which btw will become legacy.

More info about this here:
https://github.com/yahoo/mojito/pull/926

An example of the custom frame mojit here:
https://gist.github.com/4543247

**Comment by caridy** [comment]
Closing this now that the HTMLFrame refactor is in place in 0.5.3. Reference to the PR #926 for more details.
