### ISSUE TITLE
combo~ URL returning 404 in HTML5App

### ISSUE THREAD

**Issue by gvaish** [YahooArchive/mojito#982]
I am working on `todomvc` (https://github.com/addyosmani/todomvc) using Mojito.

The code is available at https://github.com/gvaish/todomvc-mojito/tree/master/todomvc-mojito-pure using `controller` with `common` affinity.
It works great.

However, after html5app build, the `index.html` has the combo URL as https://github.com/gvaish/todomvc-mojito/blob/gh-pages/pure/index.html#L18

This returns a 404.

What's the way around? Am I missing any option to `build` command?

**Comment by gvaish** [comment]
btw, I've used the following config:

```
"builds": {
    "html5app": {
        "forceRelativePaths": false,
        "attachManifest": true
    }
},
"staticHandling": {
    "appName": "todomvc",
    "useRollups": false
}
```

**Comment by caridy** [comment]
@gvaish I think we will have to revisit this use-case, specially the use of relative paths. In general, a combo is just an artifact to support your app that it happens to be part of the app itself, and it should not get affected by `forceRelativePaths` since it will not work in a pure html5 type of app.

So, change number one: disable combo for your app:

```
"yui": {
     "config": {
           "combine": false
     }
}
```

Change number two: if you want to serve yui from your app, you need some special settings to do so. If you want to serve from CDN, the default configuration should help. Here is the doc about yui configs:

http://developer.yahoo.com/cocktails/mojito/docs/topics/mojito_yui_config.html

**Comment by gvaish** [comment]
@caridy Thanks.
`yui.config.combine=false` works great.

However, cannot get `base` or `root` working... I want to serve YUI from Yahoo-CDN. How do I do that?
Nor is `comboBase` working.

All in all, it's only combine or don't. Can't use YUI served from URL like http://yui.yahooapis.com/3.8.1/build/

**Comment by gvaish** [comment]
Tried lot of hands... but failed to get `html5app` use relative `./static` path in `loader-app-base.js` that gets generated.  :-(

**Comment by caridy** [comment]
@gvaish you're facing a configuration issue. @zhouyaoji  and myself are working on a very extensive piece of doc about yui configuration in mojito, still preliminar (https://github.com/zhouyaoji/mojito/blob/docs_yui_seed_update/docs/dev_guide/topics/mojito_yui_config.rst#getting-yui-to-your-application)

In general, I tried the app using `mojito start` and it works just fine with `combine: false`, which is obviously not needed when it runs from the server. Now, the problem is when you build it into HTML. In that case, my recommendation is to have a way to configure some settings specially for that. @isao has been experimenting with this, and by creating a new environment called "build" you can easily move all the custom settings into that bucket to be used when you use build, and that way, you can have the same app that works when running mojito start and also when doing mojito build.

@isao I think this is a common use-case, and we should consider having that environment as a default environment in dimensions.json.

Aside from that, I will send you a PR later today with the proper configuration.

BTW: why do you have two apps? server and pure?

**Comment by gvaish** [comment]
@caridy Thanks. Will wait for the PR.

pure, I guess is a misnomer. I should rather call is affinity-common and may be rename server to affinity-server in the same spirit.

I wanted to demonstrate few innovative and interesting things for Mojito:
1. Common affinity for controller and how it works. How `proxy.invoke` can be used to wire binder and controller. Do not use any other framework other than base Mojito. Hence the name pure.
2. Use server affinity for controller and remaining code being essentially the same, demonstrate how `proxy.invoke` can tunnel up into the server, execute the logic in server context.

Furthermore, there two more case studies in mind:
1. Use YUI3 App framework on top of Mojito to see how to restructure the base Mojito app.
2. Use jQuery framework on Mojito. (I could have used Dojo or Backbone or anything else but jQuery is just more popular than others).

**Comment by caridy** [comment]
Ok, no PR today. I just noticed that you are running on a very edge case where assets with relative paths gets messed up with this condition in assets addon:

```
            if (content.indexOf('./') === 0) {
                content = this.getUrl(content.slice(2));
            }
```

I need more investigation on this. Adding it to trello in the meantime.

**Comment by gvaish** [comment]
Bingo. I did not dig deep into the code but I thought something like this... bleeding edge of the edge! :-)

**Comment by gvaish** [comment]
@caridy / @isao - The code is not yet pushed to npm, right?

**Comment by caridy** [comment]
No, it is not. You can get it from "develop" branch, or wait until we push to NPM in a couple of days.
